apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-wordpress
  name: mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: backend
  type: NodePort
