apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: wppod-pvc
        persistentVolumeClaim:
          claimName: wordpress-pvc
      containers:
      - image: wordpress:5.1.1-php7.3-apache
        name: wordpress
        volumeMounts:
        - mountPath: /var/www/html
          name: wppod-pvc
        
